version: '3'
services:
  database:
    #image: mysql:latest
    container_name: MyTrafficDB
    #environment:
      #MYSQL_ROOT_PASSWORD: toor
      #MYSQL_DATABASE: MyTrafficDB
    build:
      context: .
      dockerfile: database.Dockerfile
    ports:
      - "6033:3306"

  database2:
    #image: mysql:latest
    container_name: RoutesDB
    #environment:
      #MYSQL_ROOT_PASSWORD: toor
      #MYSQL_DATABASE: MyTrafficDB
    build:
      context: .
      dockerfile: database2.Dockerfile
    ports:
      - "6034:3306"        

  user_manager:
    build:
      context: .
      dockerfile: user_manager.Dockerfile
    container_name: user_manager
    depends_on:
      - database
    environment:
      DATABASE_URI: mysql+pymysql://root:toor@MyTrafficDB:3306/MyTrafficDB  
    expose:
      - "3001"
    ports:
      - "3001:3001"

  route_handler:
    build:
      context: .
      dockerfile: route_handler.Dockerfile
    container_name: route_handler
    depends_on:
      - database2
    environment:
      DATABASE_URI: mysql+pymysql://root:toor@RoutesDB:3306/RoutesDB  
    expose:
      - "3002"
    ports:
      - "3002:3002"

  nginx:
    image: nginx:alpine
    container_name: api_gateway_my_traffic
    volumes:
      - ./api_gateway.conf:/etc/nginx/conf.d/api_gateway.conf
    ports:
      - "8080:80"
    depends_on:
      - user_manager



